### ISSUE TITLE
Scala.js support

### ISSUE THREAD

**Issue by edmundnoble** [slamdata/matryoshka#25]
Are there any plans for this? Most of this project looks to be pure Scala as far as I can tell.

**Comment by sellout** [comment]
No specific plan, but I would love to have Scala.js support. I spent a few minutes trying it a month ago, and IIRC, there was a dependency or two that wasn’t available on Scala.js yet.

I would also be more than happy to accept a PR, especially since we don’t use Scala.js at SlamData, so it’s not something we’re very motivated to spend time on.

**Comment by edmundnoble** [comment]
Works great.

**Comment by sellout** [comment]
Yeah, thanks a ton!
